on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'graalvm'
    - uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - run: ./gradlew nativeCompile --no-configuration-cache
    - run: |
        brew update
        brew install imagemagick ffmpeg
    - name: Run Terminal.app and record screen
      run: |
        SLMATRIX_BIN="$(pwd)/slmatrix/build/native/nativeCompile/slmatrix"
        osascript -e "tell application \"Terminal\"" \
                  -e "ignoring application responses" \
                  -e "do script \"'$SLMATRIX_BIN' --scenes=rain\"" \
                  -e "end ignoring" \
                  -e "end tell"
        osascript -e 'tell application "Terminal" to activate'
        sleep 1
        osascript -e 'tell application "Terminal" to set bounds of front window to {0, 0, 1024, 768}'
        sleep 5
        ffmpeg -y -video_size 1024x768 -framerate 12 -f avfoundation -i "1:none" -t 10 screen-macos.webm
        killall Terminal || true
    - uses: actions/upload-artifact@v4
      with:
        name: screen-macos.webm
        path: screen-macos.webm